#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config_docker.sh

# filepath: /home/robot/ROS2_Docker_lidar_stl06/ros2_scripts/teleop
docker exec -it ${DOCKER_CONTAINER_NAME} /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run teleop_twist_joy teleop_node --ros-args -p config_file:=/ros2_ws/teleop_twist_joy.yaml"
